services:
  ######################################################################
  # psql "postgres://postgres:postgres@localhost:15432/postgres?sslmode=disable"
  ######################################################################

  pg-primary:
    image: postgres:17.9-bookworm
    container_name: pg-primary
    restart: unless-stopped
    environment:
      TZ: "Asia/Aqtau"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - pg-primary-data:/var/lib/postgresql/data
    command: >
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf
    configs:
      - source: pg_hba.conf
        target: /etc/postgresql/pg_hba.conf
        mode: "0755"
      - source: postgresql.conf
        target: /etc/postgresql/postgresql.conf
        mode: "0755"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 2s
      timeout: 2s
      retries: 10

volumes:
  pg-primary-data:

configs:
  pg_hba.conf:
    content: |
      local all         all     trust
      local replication all     trust
      host  all         all all trust
      host  replication all all trust

  postgresql.conf:
    content: |
      # log_error_verbosity:
      # TERSE, DEFAULT, VERBOSE

      # log_min_messages:
      # DEBUG5, DEBUG4, DEBUG3, DEBUG2, DEBUG1,
      # INFO, NOTICE, WARNING, ERROR, LOG, FATAL, PANIC

      listen_addresses         = '*'
      logging_collector        = off
      log_lock_waits           = on
      log_temp_files           = 0
      log_checkpoints          = on
      log_connections          = off
      log_destination          = 'stderr'
      log_error_verbosity      = 'DEFAULT'
      log_hostname             = off
      log_min_messages         = 'WARNING'
      log_timezone             = 'Asia/Aqtau'
      log_line_prefix          = '%t [%p-%l] %r %q%u@%d '
      wal_level                = replica
      max_wal_senders          = 10
      max_replication_slots    = 10
      wal_keep_size            = 64MB
      log_replication_commands = on
      datestyle                = 'iso, mdy'
      timezone                 = 'Asia/Aqtau'
      shared_preload_libraries = 'pg_stat_statements'
